(() => {
'use strict';
const C=window.AVANZA_CONTENT, repo=window.AvanzaProgress, state=repo.get(), main=document.querySelector('main');
const names=['Learn','Recognize','Build','Type','Read & Write'], spanish=['Aprende','Reconoce','Ordena','Escribe','Lee y escribe'];
let active=-1, flash=false, revealed=false, selected=null, picked=[], tokens=[], passed=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{repo.save();document.querySelector('#storage-warning').hidden=repo.available();};
// Forgive case, ordinary punctuation and spacing, but preserve lexical content.
function normalize(value){return value.normalize('NFKC').toLowerCase().replace(/[‘’]/g,"'").replace(/\b(i'm|you're|he's|she's|we're|they're|what's)\b/g,s=>({"i'm":'i am',"you're":'you are',"he's":'he is',"she's":'she is',"we're":'we are',"they're":'they are',"what's":'what is'}[s])).replace(/[.,!?;:“”"]/g,' ').replace(/\s+/g,' ').trim();}
const valid=(v,answers)=>answers.some(a=>normalize(v)===normalize(a));
const items=i=>i===0?C.cards:i===1?C.recognize:i===2?C.build:i===3?C.type:C.read;
const session=()=>state.sessions[active]||(state.sessions[active]={index:0,attempts:0});
const unlocked=i=>i===0||Array.from({length:i},(_,j)=>j).every(j=>state.completed.includes(j));
function focusMain(){main.focus();window.scrollTo(0,0);}
function home(){active=-1;flash=false;const done=state.completed.length,next=[0,1,2,3,4].find(i=>!state.completed.includes(i))??0;
 main.innerHTML=`<section class="hero"><div><div class="eyebrow">Nivel 1 · Beginning</div><h1 lang="en">Hello &<br>Introductions</h1><p>${done===5?'Unit 1 complete ✓ · ¡Lo lograste!':'Unidad 1 · Tu primera conversación en inglés.'}</p><button class="primary" data-start="${next}">${done===5?'Repasar unidad':done||state.sessions[0]?.index?'Continuar':'Empezar unidad'}</button></div><div class="ring" aria-label="${done} de 5 actividades completas"><strong>${done}<span> / 5</span></strong><span>actividades completas</span></div></section><div class="section-head"><h2>Tu recorrido</h2><span class="pill">Paso a paso</span></div><section class="activities" aria-label="Actividades de la unidad">${names.map((name,i)=>`<button class="activity ${state.completed.includes(i)?'done':''}" data-start="${i}" ${!unlocked(i)?'disabled':''}><span class="number">0${i+1} · ${state.completed.includes(i)?'✓ Completa':unlocked(i)?'Disponible':'Bloqueada'}</span><strong lang="en">${name}</strong><small>${spanish[i]}</small></button>`).join('')}</section><div class="lower"><section class="panel review-panel"><div class="eyebrow">Practica a tu ritmo</div><h2>Flashcards</h2><p class="muted">Saludos, presentaciones y <span lang="en">to be</span>.</p><button data-action="flash">Repasar tarjetas</button></section><section class="panel"><details><summary>Próximas unidades <span class="pill">9</span></summary><ul class="future-list">${C.units.slice(1).map((name,i)=>`<li><b>${i+2}. ${name}</b><span>Próximamente</span></li>`).join('')}</ul></details><p class="subtle">Más inglés, una unidad a la vez.</p></section></div><section class="levels" aria-label="Próximos niveles">${C.levels.slice(1).map(l=>`<div><strong>Nivel ${l.id} · ${l.name}</strong>Próximamente / Coming soon</div>`).join('')}</section>`;focusMain();}
function start(i){if(!unlocked(i))return;active=i;flash=false;const s=session();if(!Number.isInteger(s.index)||s.index<0||s.index>=items(i).length)s.index=0;save();render();focusMain();}
function shell(title,index,total,body){main.innerHTML=`<div class="workspace"><button class="back" data-action="home">Volver al inicio</button><div class="workspace-top"><div><div class="eyebrow">Unidad 1 · ${flash?'Repaso':`Actividad ${active+1} de 5`}</div><h1>${title}</h1></div><span class="pill">${index+1} / ${total}</span></div><div class="progress" role="progressbar" aria-label="Progreso de la actividad" aria-valuenow="${index}" aria-valuemin="0" aria-valuemax="${total}"><div style="width:${100*index/total}%"></div></div>${body}</div>`;}
function render(){passed=false;selected=null;picked=[];const s=session(), list=items(active), item=list[s.index];
 if(active===0){shell('Aprende · Learn',s.index,list.length,`<section class="card learn"><span class="eyebrow">${s.index>=22?'To be · Ser / estar':'Inglés para conocernos'}</span><h2 lang="en">${esc(item[0])}</h2><div class="translation">${esc(item[1])}</div><p class="note">${esc(item[2])}</p></section><div class="row end"><button data-action="previous" ${s.index===0?'disabled':''}>Anterior</button><button class="dark" data-action="learn-next">${s.index===list.length-1?'Terminar · Finish':'Siguiente · Next card'}</button></div>`);return;}
 const prompt=active===2?item[0]:item.q;
 shell(`${spanish[active]} · ${names[active]}`,s.index,list.length,`<section class="card"><p class="instructions">${active===1?'Elige la respuesta correcta.':active===2?'Toca las palabras en orden. Toca una palabra para quitarla.':'Escribe la respuesta en inglés.'}<span lang="en">${active===1?'Choose the correct answer.':active===2?'Tap the words in order. Tap a selected word to remove it.':'Type the answer in English.'}</span></p>${active===4?`<aside class="reading"><p lang="en">${esc(C.reading)}</p><small>${esc(C.glossary)}</small></aside>`:''}<div class="prompt">${esc(prompt)}</div><form id="answer-form">${active===2?'<div id="built" class="tokens answer-line" aria-label="Tu oración"></div><label>Palabras / Word bank</label><div id="bank" class="tokens"></div>':item.options?`<div class="options" role="group" aria-label="Respuestas">${item.options.map((v,i)=>`<button type="button" data-choice="${i}" aria-pressed="false">${esc(v)}</button>`).join('')}</div>`:'<label for="answer">Tu respuesta / Your answer</label><input id="answer" type="text" autocomplete="off" autocapitalize="sentences" spellcheck="false" required placeholder="Escribe en inglés…">'}<div id="feedback" class="feedback" role="status" aria-live="polite"></div><div class="row"><button type="submit" class="dark" id="check">Comprobar · Check</button><button type="button" data-action="hint" id="hint">Pista</button><button type="button" class="dark" data-action="next" id="next" hidden>Siguiente · Next</button></div></form></section>`);
 if(active===2){tokens=item[1].split(' ').map((word,id)=>({word,id}));for(let i=tokens.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[tokens[i],tokens[j]]=[tokens[j],tokens[i]];}if(tokens.map(t=>t.word).join(' ')===item[1])tokens.reverse();drawTokens();}
}
function drawTokens(){document.querySelector('#built').innerHTML=picked.length?picked.map(id=>`<button type="button" data-remove="${id}">${esc(tokens.find(t=>t.id===id).word)}</button>`).join(''):'<span class="empty">Tu oración aparece aquí.</span>';document.querySelector('#bank').innerHTML=tokens.filter(t=>!picked.includes(t.id)).map(t=>`<button type="button" data-token="${t.id}">${esc(t.word)}</button>`).join('');}
function feedback(text,correct=false){const box=document.querySelector('#feedback');box.textContent=text;box.className='feedback'+(correct?' correct':'');}
function check(){if(passed)return;const item=items(active)[session().index];let answer=active===2?picked.map(id=>tokens.find(t=>t.id===id).word).join(' '):item.options?(selected===null?'':item.options[selected]):document.querySelector('#answer').value;
 if(!answer.trim()){feedback('Primero escribe o elige una respuesta.');return;}session().attempts++;save();const correct=active===2?valid(answer,[item[1]]):item.options?answer===item.answer:valid(answer,item.answers);
 if(correct){passed=true;feedback('¡Bien hecho! '+(active===2?item[1]:item.answers?.[0]||item.answer),true);document.querySelectorAll('#answer-form input,#answer-form .options button,#answer-form .tokens button').forEach(el=>el.disabled=true);document.querySelector('#check').hidden=true;document.querySelector('#hint').hidden=true;const next=document.querySelector('#next');next.hidden=false;next.textContent=session().index===items(active).length-1?'Terminar · Finish':'Siguiente · Next';next.focus();}else feedback('Inténtalo otra vez. '+(active===2?'Empieza con '+item[1].split(' ')[0]+'.':item.hint));}
function finish(){const i=active;const first=!state.completed.includes(i);if(first)state.completed.push(i);state.sessions[i]={index:0,attempts:0};save();const all=state.completed.length===5;main.innerHTML=`<div class="workspace"><section class="card success"><div class="check">✓</div><div class="eyebrow">${names[i]} · Completa</div><h1>${all?'UNIT 1 COMPLETE ✓':'¡Un paso más!'}</h1><p class="muted">${all?'Ya practicaste tu primera conversación en inglés.':`${state.completed.length} de 5 actividades completas.`}</p><div class="row">${i<4?`<button class="dark" data-start="${i+1}">Continuar · ${names[i+1]}</button>`:'<button class="dark" data-action="home">Ver mi progreso</button>'}<button data-start="${i}">Repetir actividad</button>${i<4?'<button data-action="home">Inicio</button>':'<button data-action="flash">Repasar tarjetas</button>'}</div></section></div>`;passed=false;focusMain();}
function advance(){const s=session();if(s.index===items(active).length-1){finish();return;}s.index++;save();render();focusMain();}
function showFlash(){flash=true;active=-1;revealed=false;if(!Number.isInteger(state.flash)||state.flash<0||state.flash>=C.cards.length)state.flash=0;renderFlash();focusMain();}
function renderFlash(){const index=state.flash,card=C.cards[index];shell('Flashcards',index,C.cards.length,`<section class="card learn"><div class="eyebrow">English / Inglés</div><h2 lang="en">${esc(card[0])}</h2>${revealed?`<div class="translation">${esc(card[1])}</div><p class="note">${esc(card[2])}</p>`:'<p class="muted">¿Qué significa?</p>'}<button class="reveal" data-action="reveal">${revealed?'Ocultar significado':'Ver significado · Show meaning'}</button></section><div class="row end flash-tools"><button data-action="flash-prev" ${index===0?'disabled':''}>Anterior</button><button class="dark" data-action="flash-next">${index===C.cards.length-1?'Terminar repaso · Finish':'Siguiente · NEXT CARD'}</button></div><p class="subtle">Repaso libre · Las tarjetas no completan las cinco actividades.</p>`);}
main.addEventListener('submit',e=>{if(e.target.id==='answer-form'){e.preventDefault();check();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.start!==undefined){start(Number(b.dataset.start));return;}if(b.dataset.choice!==undefined){selected=Number(b.dataset.choice);document.querySelectorAll('[data-choice]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',el===b?'true':'false');});return;}if(b.dataset.token!==undefined&&!passed){picked.push(Number(b.dataset.token));drawTokens();return;}if(b.dataset.remove!==undefined&&!passed){picked=picked.filter(id=>id!==Number(b.dataset.remove));drawTokens();return;}
 switch(b.dataset.action){case'home':home();break;case'flash':showFlash();break;case'previous':if(session().index>0){session().index--;save();render();}break;case'learn-next':if(active===0)advance();break;case'next':if(passed)advance();break;case'hint':{const item=items(active)[session().index];feedback(active===2?'Modelo: '+item[1]:item.hint);break;}case'reveal':revealed=!revealed;renderFlash();break;case'flash-prev':state.flash=Math.max(0,state.flash-1);revealed=false;save();renderFlash();break;case'flash-next':if(state.flash===C.cards.length-1){state.flash=0;save();main.innerHTML='<div class="workspace"><section class="card success"><div class="check">✓</div><h1>¡Repaso completo!</h1><p>28 tarjetas repasadas.</p><div class="row"><button class="dark" data-action="flash">Repasar otra vez</button><button data-action="home">Inicio</button></div></section></div>';focusMain();}else{state.flash++;revealed=false;save();renderFlash();}break;}
});
save();home();
})();
